export const SET_PRODUCT_FILTER = 'SET_PRODUCT_FILTER';
export const SET_BROWSER_FILTER = 'SET_BROWSER_FILTER';
export const SET_SEVERITY_FILTER = 'SET_SEVERITY_FILTER';
export const SET_PRIORITY_FILTER = 'SET_PRIORITY_FILTER';
export const SET_TYPE_FILTER = 'SET_TYPE_FILTER';
export const SET_STATUS_FILTER = 'SET_STATUS_FILTER';