export const SET_LOCATION = 'SET_LOCATION';
export const SET_PRIMARY_NAVIGATIONS = 'SET_NAVIGATIONS';
export const SET_SECONDARY_NAVIGATIONS = 'SET_SECONDARY_NAVIGATIONS';
export const SET_IS_SIDEBAR_OPEN = 'SET_IS_SIDEBAR_OPEN';