export const SET_SORT_OPTION = 'SET_SORT_OPTION';
export const SET_SORT_MODE = 'SET_SORT_MODE';
export const SET_TICKET_INFO_MODAL_IS_SHOWING = "SET_TICKET_INFO_MODAL_IS_SHOWING";
export const SET_SELECTED_FILTER = 'SET_SELECTED_FILTER';